Feature/dev/campaign evaluation
NextIntern/NextIntern-Backend pull request #19
Opened 2024-06-14 03:54 UTC by dungpha13

2024-06-14 17:22 UTC, hdang09 requested changes

2024-06-14 17:22 UTC, hdang09 commented on SWD.NextIntern.API/Controllers/Campaign/CampaignController.cs
> +        [HttpPut("")]
Cái này để `[HttpPut("update")]` đi

2024-06-14 17:22 UTC, hdang09 commented on SWD.NextIntern.API/Controllers/CampaignEvaluation/CampaignEvaluationController.cs
> +        [HttpPut("")]
Cái này để [HttpPut("update")] đi

2024-06-14 17:22 UTC, hdang09 commented on SWD.NextIntern.Service/Common/Mapping/AutoMapperProfile.cs
> +            //    .ForMember(dest => dest.ModifyDate, opt => opt.MapFrom(src => src.ModifyDate));
comment này có xài nữa kh, nếu kh xài thì xóa đi nha

2024-06-14 17:22 UTC, hdang09 commented on SWD.NextIntern.Service/Services/CampaignService/Create/CreateCampaignCommand.cs
> +        public string? UniversityId { get; set; }
UniversityId sao string thế

2024-06-14 17:24 UTC, hdang09 commented
![image](https://github.com/NextIntern/NextIntern-Backend/assets/96512007/e304857f-44d7-435a-a96f-f1cd119d8c75)
Đổi tên PR theo task jira nha

2024-06-14 17:27 UTC, hdang09 commented on SWD.NextIntern.Repository/Repositories/UserRepository.cs
> +        //}
Comment kh xài xóa đi

2024-06-14 17:27 UTC, hdang09 commented on SWD.NextIntern.Service/Services/CampaignService/Create/CreateCampaignCommandValidation.cs
> +        }
Validate start date, end date lớn hơn current date

2024-06-15 10:35 UTC, hdang09 approved these changes

2024-06-15 10:35 UTC, merged

2024-06-15 11:43 UTC, dungpha13 commented on SWD.NextIntern.Service/Services/CampaignService/Create/CreateCampaignCommand.cs
> +        public string? UniversityId { get; set; }
nhận vào là string đăng ơi r mới convert qua guid